log:
  file:  ./currencier.log
api:
  httpport:  4444
db:
  dsn:  host=db port=5432 user=igor password=igor dbname=currencier sslmode=disable
  dialect: pgx
update:
  time: 5s
  source:  http://www.cbr.ru/scripts/XML_daily.asp